# Docker Buildfile for ROCm 6.4 to recompile PyTorch/Torchvision/Torchaudio 
# use a RX5(x)0 / Polaris / gfx803 AMD GPU with ROCm 6.4
# created, build and compiled by Robert Rosenbusch at April 2025

### Build rocm6_gfx803_base:6.4 first! Read the README.md, it could save lifetime :P
FROM rocm6_gfx803_base:6.4

SHELL ["/bin/bash", "-c"]  
ENV WHISPERX_GUI_PORT=7860 \
    DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONENCODING==UTF-8 \
    REQS_FILE='requirements.txt' \
    COMMANDLINE_ARGS='' \
    PIP_ROOT_USER_ACTION='ignore' \
    ### For your AMD GPU
    PYTORCH_ROCM_ARCH=gfx803 
    
###########
### Build PyTorch
###########
WORKDIR /    
ENV PYTORCH_GIT_VERSION="release/2.6"
RUN echo "** Checkout PyTorch: ${PYTORCH_GIT_VERSION} **" && \  
    git clone --recursive https://github.com/ROCm/pytorch.git -b ${PYTORCH_GIT_VERSION} /pytorch && \
    true

WORKDIR /pytorch
RUN echo "** BUILDING PYTORCH *** " && \ 
    python3 --version && \
    dpkg -r --force-depends python3-yaml python3-filelock &&\
    mkdir -p /pytorch/dist && \
    python3 setup.py clean && \
    pip3 install --break-system-packages -r ${REQS_FILE} && \
    python3 tools/amd_build/build_amd.py && \
    python3 setup.py bdist_wheel && \
    pip3 install --break-system-packages dist/torch*.whl && \
    true     

###########
### Build TorchVision
###########
ENV TORCH_GIT_VERSION="release/0.21"
RUN echo "** Checkout Torchvision Version: ${TORCH_GIT_VERSION} ** " && \ 
   git clone https://github.com/pytorch/vision.git -b ${TORCH_GIT_VERSION} /vision && \
   true

WORKDIR /vision
RUN echo "** BUILDING PYTORCH *** " && \ 
    python3 setup.py bdist_wheel && \
    pip install --break-system-packages  dist/torchvision-*.whl && \
    mkdir -p /vision/dist && \
    true

###########
### Build TorchAudio
###########
ENV TORCHAUDIO_GIT_VERSION="v2.6.0"
RUN echo "** Checkout Torchaudio Version: ${TORCHAUDIO_GIT_VERSION} **" && \ 
    git clone https://github.com/pytorch/audio.git -b ${TORCHAUDIO_GIT_VERSION} /audio && \
    true

WORKDIR /audio
RUN echo "** BUILDING Torchaudio **" && \
    python3 setup.py bdist_wheel && \
    pip install --break-system-packages dist/*.whl && \
    true 

######
# End of building pytorch and torchvision WHL-Files
###########

CMD ["/bin/bash","-c"]